FROM rocm/dev-ubuntu-24.04

WORKDIR /development

RUN apt-get update && \
    apt-get dist-upgrade -y && \
    apt-get install -y apt-utils autoconf autotools-dev bash-completion bison \
        build-essential chrpath cmake curl flex gettext git-core gnupg2 libnuma1 libopenmpi-dev \
        libpapi-dev libpfm4-dev librpm-dev libtool libudev1 lsb-release m4 \
        python3.12 python3.12-venv python3.12-dev python3-pip libsqlite3-dev rpm texinfo wget iproute2


# Allows running git commands in /development
RUN git config --global --add safe.directory /development
RUN git config --global --add safe.directory /development/external/timemory

# Setup python 3.12 venv
RUN python3.12 -m venv /opt/py3.12
ENV PATH="/opt/py3.12/bin:${PATH}"
RUN pip install --upgrade pip && \
    pip install numpy perfetto dataclasses

# Allow mpiexec to run as root
ENV OMPI_ALLOW_RUN_AS_ROOT=1
ENV OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

CMD ["/bin/bash"]
