ARG DISTRO=opensuse/leap
ARG VERSION=15.5
FROM ${DISTRO}:${VERSION}

ENV HOME /root
ENV SHELL /bin/bash
ENV BASH_ENV /etc/bash.bashrc
ENV DEBIAN_FRONTEND noninteractive

WORKDIR /tmp
SHELL [ "/bin/bash", "-c" ]

ENV PATH /usr/local/bin:${PATH}

ARG EXTRA_PACKAGES=""
ARG ELFUTILS_DOWNLOAD_VERSION="0.188"
ARG BOOST_DOWNLOAD_VERSION="1.79.0"
ARG NJOBS="8"

RUN set +e; \
    zypper --non-interactive -i --gpg-auto-import-keys refresh; \
    zypper --non-interactive -i patch; \
    zypper --non-interactive -i patch; \
    zypper --non-interactive -i --gpg-auto-import-keys refresh; \
    exit 0

RUN zypper --non-interactive update -y && \
    zypper --non-interactive dist-upgrade -y && \
    zypper --non-interactive install -y -t pattern devel_basis && \
    zypper --non-interactive install -y binutils-gold chrpath cmake curl dpkg-devel \
        gcc-c++ git libnuma-devel openmpi3-devel papi-devel python3-pip \
        rpm-build vim wget iproute2 && \
    zypper --non-interactive clean --all && \
    python3 -m pip install 'cmake==3.21' perfetto

COPY ./dyninst-source /tmp/dyninst

RUN cd /tmp/dyninst && \
    cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_BOOST=ON -DBUILD_TBB=ON \
        -DBUILD_ELFUTILS=ON -DBUILD_LIBIBERTY=ON \
        -DElfUtils_DOWNLOAD_VERSION=${ELFUTILS_DOWNLOAD_VERSION} \
        -DBOOST_DOWNLOAD_VERSION=${BOOST_DOWNLOAD_VERSION} && \
    cmake --build build --target all --parallel ${NJOBS} && \
    cmake --build build --target install --parallel ${NJOBS} && \
    cd /tmp && \
    shopt -s dotglob extglob && \
    rm -rf *

ARG PYTHON_VERSIONS="6 7 8 9 10 11 12 13"

RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh && \
    bash miniforge.sh -b -p /opt/conda && \
    export PATH="/opt/conda/bin:${PATH}" && \
    conda config --set always_yes yes --set changeps1 no && \
    conda update -c conda-forge -n base conda && \
    for i in ${PYTHON_VERSIONS}; do conda create -n py3.${i} -c conda-forge python=3.${i} pip numpy; done && \
    for i in ${PYTHON_VERSIONS}; do /opt/conda/envs/py3.${i}/bin/python -m pip install numpy perfetto dataclasses; done && \
    conda clean -a -y && \
    cd /tmp && \
    shopt -s dotglob extglob && \
    rm -rf *

WORKDIR /home
SHELL [ "/bin/bash", "--login", "-c" ]
